#!/usr/bin/env python3
"""Cut a full-body character picture into body parts for the cut-out renderer.

Usage: python3 tools/make_cutout.py <worf.jpg> src/cutouts.js

Each part is a polygon on the source picture plus two points on it: `pivot`,
the joint it hangs from, and `tip`, the joint at its other end. The game lines
pivot -> tip up with the matching bone of its skeleton every frame, so the
parts move with the existing animations. Coordinates below are for the
329x1024 Worf picture. Writes a JS file with the parts embedded as data URIs.
"""
import base64
import io
import json
import sys

from PIL import Image, ImageDraw

# Where the hand holding the phaser covers the body: painted over with the
# tunic (above the waist) and trousers (below) so the torso has no extra hand.
PATCHES = [
    ((62, 322, 142, 400), (200, 150, 12)),
    ((62, 400, 142, 420), (10, 10, 12)),
]

PARTS = {
    # The figure's own right arm hangs straight, so it serves for both arms.
    'upperArm': {
        'poly': [(246, 186), (300, 205), (318, 260), (326, 330), (328, 440), (266, 440), (262, 330), (254, 262)],
        'pivot': (282, 215), 'tip': (296, 432),
    },
    'forearm': {
        'poly': [(264, 424), (329, 424), (329, 520), (322, 590), (282, 598), (272, 520)],
        'pivot': (296, 432), 'tip': (300, 572),
    },
    # Torso with the waist and hips; the arms are trimmed off the sides.
    'torso': {
        'poly': [(66, 160), (240, 160), (258, 196), (262, 330), (262, 440), (258, 610), (62, 610), (66, 330)],
        'pivot': (160, 592), 'tip': (162, 178),
    },
    'head': {
        'poly': [(86, 0), (244, 0), (244, 120), (214, 172), (110, 172), (86, 120)],
        'pivot': (162, 170), 'tip': (162, 20),
    },
    # The figure's left leg, whose boot points to the right: both legs.
    'thigh': {
        'poly': [(160, 575), (268, 575), (266, 800), (180, 800), (164, 700)],
        'pivot': (210, 600), 'tip': (222, 790),
    },
    'shin': {
        'poly': [(178, 780), (266, 780), (268, 945), (329, 975), (329, 1012), (196, 1012), (186, 900)],
        'pivot': (222, 790), 'tip': (226, 985),
    },
}


def remove_background(im):
    """Near-white pixels joined to the picture's edge become transparent."""
    im = im.convert('RGBA')
    w, h = im.size
    px = im.load()
    white = lambda p: p[0] > 228 and p[1] > 228 and p[2] > 228
    seen = set()
    stack = [(x, y) for x in range(w) for y in (0, h - 1)] + [(x, y) for y in range(h) for x in (0, w - 1)]
    while stack:
        x, y = stack.pop()
        if (x, y) in seen or not (0 <= x < w and 0 <= y < h):
            continue
        seen.add((x, y))
        if not white(px[x, y]):
            continue
        px[x, y] = (0, 0, 0, 0)
        stack += [(x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)]
    return im


def main(src, out):
    im = remove_background(Image.open(src))
    d = ImageDraw.Draw(im)
    for box, color in PATCHES:
        d.rectangle(box, fill=color + (255,))
    parts = {}
    for name, spec in PARTS.items():
        mask = Image.new('L', im.size, 0)
        ImageDraw.Draw(mask).polygon(spec['poly'], fill=255)
        cut = Image.new('RGBA', im.size, (0, 0, 0, 0))
        cut.paste(im, (0, 0), mask)
        box = cut.getbbox()
        cut = cut.crop(box)
        buf = io.BytesIO()
        cut.save(buf, 'PNG', optimize=True)
        parts[name] = {
            'src': 'data:image/png;base64,' + base64.b64encode(buf.getvalue()).decode(),
            'pivot': [spec['pivot'][0] - box[0], spec['pivot'][1] - box[1]],
            'tip': [spec['tip'][0] - box[0], spec['tip'][1] - box[1]],
        }
    with open(out, 'w') as f:
        f.write('// Generated by tools/make_cutout.py: body parts cut from a character picture.\n')
        f.write('const CUTOUTS = { worf: ' + json.dumps(parts) + ' };\n')
    print(out, sum(len(p['src']) for p in parts.values()) // 1024, 'KB')


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
