#!/usr/bin/env python3
"""Cut a held weapon out of a picture with a transparent backdrop.

Usage: python3 tools/make_prop.py <picture> src/props.js

Writes PROPS.<name> = {src, pivot, tip}: a small WebP cut to the weapon, the
point the hand holds (pivot) and a point the renderer lines up with the
forearm (tip), both in the saved picture's pixels.
"""
import base64
import io
import json
import sys

from PIL import Image

# Picture coordinates (1100x1100 bat'leth picture): the middle grip on the
# spine, and a point straight out from it toward the blades.
BATLETH = {'name': 'batleth', 'height': 420, 'pivot': (280, 432), 'tip': (600, 470)}


def main(src, out):
    cfg = BATLETH
    im = Image.open(src).convert('RGBA')
    box = im.getchannel('A').point(lambda a: 255 if a > 8 else 0).getbbox()
    im = im.crop(box)
    k = cfg['height'] / im.height
    im = im.resize((round(im.width * k), cfg['height']), Image.LANCZOS)
    at = lambda p: [round((p[0] - box[0]) * k, 1), round((p[1] - box[1]) * k, 1)]
    buf = io.BytesIO()
    im.save(buf, 'WEBP', quality=88)
    data = {'src': 'data:image/webp;base64,' + base64.b64encode(buf.getvalue()).decode(),
            'pivot': at(cfg['pivot']), 'tip': at(cfg['tip'])}
    with open(out, 'w') as f:
        f.write('// Generated by tools/make_prop.py: weapons cut from reference pictures.\n')
        f.write('var PROPS = window.PROPS || {};\n')
        f.write(f"PROPS.{cfg['name']} = {json.dumps(data)};\n")
    print(out, im.size, len(buf.getvalue()) // 1024, 'KB')


if __name__ == '__main__':
    main(*sys.argv[1:3])
