#!/usr/bin/env python3
"""Cut a held weapon out of a picture.

Usage: python3 tools/make_prop.py <name> <picture> src/props.js

Adds or replaces PROPS.<name> = {src, pivot, tip} in src/props.js: a small
WebP cut to the weapon, the point the hand holds (pivot) and a point the
renderer lines up with the forearm (tip), both in the saved picture's pixels.
The picture either has a transparent backdrop or a plain light one, which is
removed by flooding in from the edges.
"""
import base64
import io
import json
import os
import re
import sys

import numpy as np
from PIL import Image, ImageFilter

# Coordinates are in the original picture's pixels.
CONFIGS = {
    # 1100x1100 bat'leth, transparent: the middle grip on the spine, and a
    # point straight out from it toward the blades.
    'batleth': {'height': 420, 'pivot': (280, 432), 'tip': (600, 470)},
    # 1920x862 TNG hand phaser on a light backdrop: where the fist closes on
    # the grip, and the emitter at the front.
    'phaser': {'width': 300, 'pivot': (430, 455), 'tip': (1800, 470), 'backdrop': True},
}


def flood_backdrop(im):
    """Alpha for everything not reachable from the edges through near-white pixels."""
    a = np.asarray(im.convert('RGB')).astype(int)
    mx, mn = a.max(2), a.min(2)
    cand = (mn > 238) & (mx - mn < 14)
    reach = np.zeros_like(cand)
    reach[0, :] = reach[-1, :] = reach[:, 0] = reach[:, -1] = True
    reach &= cand
    while True:
        n = reach.copy()
        n[1:] |= reach[:-1]
        n[:-1] |= reach[1:]
        n[:, 1:] |= reach[:, :-1]
        n[:, :-1] |= reach[:, 1:]
        n &= cand
        if (n == reach).all():
            break
        reach = n
    mask = Image.fromarray(((~reach) * 255).astype(np.uint8), 'L')
    # Shave the light fringe, then soften the edge.
    return mask.filter(ImageFilter.MinFilter(3)).filter(ImageFilter.GaussianBlur(1.2))


def main(name, src, out):
    cfg = CONFIGS[name]
    im = Image.open(src).convert('RGBA')
    if cfg.get('backdrop'):
        im.putalpha(flood_backdrop(im))
    box = im.getchannel('A').point(lambda a: 255 if a > 8 else 0).getbbox()
    im = im.crop(box)
    k = cfg['height'] / im.height if 'height' in cfg else cfg['width'] / im.width
    im = im.resize((round(im.width * k), round(im.height * k)), Image.LANCZOS)
    at = lambda p: [round((p[0] - box[0]) * k, 1), round((p[1] - box[1]) * k, 1)]
    buf = io.BytesIO()
    im.save(buf, 'WEBP', quality=88)
    data = {'src': 'data:image/webp;base64,' + base64.b64encode(buf.getvalue()).decode(),
            'pivot': at(cfg['pivot']), 'tip': at(cfg['tip'])}
    lines = open(out).read().splitlines() if os.path.exists(out) else []
    lines = [l for l in lines if l.startswith('PROPS.') and not l.startswith(f'PROPS.{name} =')]
    lines.append(f'PROPS.{name} = {json.dumps(data)};')
    with open(out, 'w') as f:
        f.write('// Generated by tools/make_prop.py: weapons cut from reference pictures.\n')
        f.write('var PROPS = window.PROPS || {};\n')
        f.write('\n'.join(sorted(lines)) + '\n')
    im.save(os.environ.get('PROP_PREVIEW', os.devnull) if os.environ.get('PROP_PREVIEW') else io.BytesIO(), 'PNG')
    print(out, name, im.size, len(buf.getvalue()) // 1024, 'KB', data['pivot'], data['tip'])


if __name__ == '__main__':
    main(*sys.argv[1:4])
