#!/usr/bin/env python3
"""Pull the pieces the painted renderer needs out of a reference picture.

Usage: python3 tools/make_painted_assets.py <seven.webp> src/painted-seven.js

The painted renderer (src/painted.js) draws the body, arms, legs and boots as
smooth shaded shapes. From the picture it takes only what can't be painted
well in code: the head and the two fists, cut from the backdrop with a soft
edge, and two small seamless texture tiles (the suit's scaly fabric and the
sleeve knit) that are laid over the painted shapes. Coordinates are for the
2000x1116 side-view picture of Seven in a fighting stance on white.
"""
import base64
import io
import json
import sys

import numpy as np
from PIL import Image, ImageChops, ImageDraw, ImageFilter

PIECES = {
    # pivot: where it attaches (base of the neck, the wrist); tip: a point the
    # renderer lines up with the bone (the top of the head, the knuckles).
    'head': {'poly': [(948, 28), (1062, 28), (1092, 80), (1086, 124), (1075, 140), (1069, 176), (1044, 204), (986, 204), (952, 150)],
             'pivot': (1012, 196), 'tip': (1010, 40)},
    'fist': {'poly': [(1071, 164), (1140, 164), (1140, 206), (1121, 229), (1098, 223), (1077, 213), (1071, 195)],
             'pivot': (1097, 220), 'tip': (1106, 170)},
    'borgFist': {'poly': [(1170, 174), (1244, 174), (1244, 230), (1224, 250), (1199, 250), (1179, 238), (1170, 216)],
                 'pivot': (1204, 242), 'tip': (1212, 182)},
}
# Patches for the texture tiles: plain stretches of suit and sleeve.
TEXTURES = {
    'suit': (998, 596, 1038, 636),
    'sleeve': (1064, 264, 1086, 286),
}


def figure_mask(im):
    """Soft alpha for everything that isn't the white backdrop."""
    a = np.asarray(im).astype(int)
    mx, mn = a.max(2), a.min(2)
    cand = (mx > 205) & (mx - mn < 22)
    reach = np.zeros_like(cand)
    reach[0, :] = reach[-1, :] = reach[:, 0] = reach[:, -1] = True
    reach &= cand
    while True:
        n = reach.copy()
        n[1:] |= reach[:-1]
        n[:-1] |= reach[1:]
        n[:, 1:] |= reach[:, :-1]
        n[:, :-1] |= reach[:, 1:]
        n &= cand
        if (n == reach).all():
            break
        reach = n
    mask = Image.fromarray(((~reach) * 255).astype(np.uint8), 'L')
    # Shave the light fringe, then soften the edge.
    return mask.filter(ImageFilter.MinFilter(3)).filter(ImageFilter.GaussianBlur(1.0))


def data_uri(img, fmt):
    buf = io.BytesIO()
    if fmt == 'webp':
        img.save(buf, 'WEBP', quality=92)
    else:
        img.save(buf, 'PNG', optimize=True)
    return f'data:image/{fmt};base64,' + base64.b64encode(buf.getvalue()).decode()


def texture_tile(im, box):
    """Seamless gray detail tile (128 = no change), for a soft-light overlay."""
    # The fabric's grain relative to its local brightness; blurred with a
    # margin so the patch edges don't leave a ring.
    pad = 16
    x0, y0, x1, y1 = box
    wide = im.crop((x0 - pad, y0 - pad, x1 + pad, y1 + pad)).convert('L')
    blur = wide.filter(ImageFilter.GaussianBlur(6))
    inner = (pad, pad, pad + x1 - x0, pad + y1 - y0)
    lum = np.asarray(wide.crop(inner)).astype(float)
    base = np.asarray(blur.crop(inner)).astype(float) + 1
    detail = np.clip(128 + (lum / base - 1) * 160, 0, 255).astype(np.uint8)
    tile = Image.fromarray(detail, 'L')
    # Mirror into a 2x2 block so the edges meet.
    w, h = tile.size
    out = Image.new('L', (w * 2, h * 2))
    out.paste(tile, (0, 0))
    out.paste(tile.transpose(Image.FLIP_LEFT_RIGHT), (w, 0))
    out.paste(tile.transpose(Image.FLIP_TOP_BOTTOM), (0, h))
    out.paste(tile.transpose(Image.ROTATE_180), (w, h))
    return out


def main(src, out):
    im = Image.open(src).convert('RGB')
    alpha = figure_mask(im)
    data = {'pieces': {}, 'textures': {}}
    for name, spec in PIECES.items():
        poly = Image.new('L', im.size, 0)
        ImageDraw.Draw(poly).polygon(spec['poly'], fill=255)
        # The cut edges fade (they sit over painted shapes); the outline stays.
        poly = poly.filter(ImageFilter.GaussianBlur(2.5))
        piece = im.convert('RGBA')
        piece.putalpha(ImageChops.multiply(alpha, poly))
        box = piece.getchannel('A').point(lambda v: 255 if v > 2 else 0).getbbox()
        piece = piece.crop(box)
        data['pieces'][name] = {
            'src': data_uri(piece, 'webp'),
            'pivot': [spec['pivot'][0] - box[0], spec['pivot'][1] - box[1]],
            'tip': [spec['tip'][0] - box[0], spec['tip'][1] - box[1]],
        }
    for name, box in TEXTURES.items():
        data['textures'][name] = data_uri(texture_tile(im, box), 'png')
    with open(out, 'w') as f:
        f.write('// Generated by tools/make_painted_assets.py from a reference picture of Seven.\n')
        f.write('var PAINTED = window.PAINTED || {};\n')
        f.write('PAINTED.seven = ' + json.dumps(data) + ';\n')
    print(out, sum(len(v['src']) for v in data['pieces'].values()) // 1024, 'KB pieces')
    preview = Image.new('RGBA', (900, 300), (90, 90, 110, 255))
    x = 0
    for name in PIECES:
        p = Image.open(io.BytesIO(base64.b64decode(data['pieces'][name]['src'].split(',')[1])))
        preview.alpha_composite(p, (x, 0))
        x += p.width + 10
    for name in TEXTURES:
        t = Image.open(io.BytesIO(base64.b64decode(data['textures'][name].split(',')[1]))).convert('RGBA')
        preview.alpha_composite(t, (x, 0))
        x += t.width + 10
    preview.save(out + '.preview.png')


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
