#!/usr/bin/env python3
"""Pack a fighter's generated body parts into src/parts-<id>.js.

Usage: python3 tools/pack_parts.py <id> <folder of cut-out part PNGs> src/parts-<id>.js

Each part was painted on its own (Nano Banana), cut out and graded to match
the rest. For each one this records two joint points in the picture's pixels:
`pivot` and `tip`. The renderer (src/painted.js drawPart) pins pivot to one
joint and tip to the other (shoulder and elbow for the upper arm, hip and neck
for the torso, ...), so the part follows the skeleton. `mid` is the part's
width across the middle, used to fit it to the limb's thickness.
"""
import base64
import io
import json
import sys

import numpy as np
from PIL import Image

# Joint points per part, in the cut-out pictures' pixels.
ANCHORS = {
    'mando': {
        'upperArm': {'pivot': (68, 60), 'tip': (78, 300)},  # shoulder, elbow
        'forearm': {'pivot': (74, 62), 'tip': (98, 336)},  # elbow, wrist
        'glove': {'pivot': (77, 8), 'tip': (80, 160)},  # wrist (tapered to slip into the sleeve), knuckles
        'thigh': {'pivot': (76, 70), 'tip': (92, 372)},  # hip, knee
        'shin': {'pivot': (84, 58), 'tip': (66, 392)},  # knee, ankle
        'foot': {'pivot': (62, 120), 'tip': (62, 166)},  # ankle bone (toward the heel), the sole below it (sets the boot's size)
        'torso': {'pivot': (118, 468), 'tip': (108, 22)},  # hip, base of the neck
        'jetpack': {'pivot': (232, 280), 'tip': (232, 44), 'nozzle': (206, 418)},  # lower and upper mount on its back face
        'helmet': {'pivot': (140, 286), 'tip': (126, 4)},  # where the neck enters, top of the dome
    },
    'worf': {
        'upperArm': {'pivot': (60, 52), 'tip': (72, 330)},
        'forearm': {'pivot': (56, 40), 'tip': (56, 340)},
        'glove': {'pivot': (66, 6), 'tip': (74, 194), 'file': 'fist'},  # bare fist
        'thigh': {'pivot': (72, 40), 'tip': (74, 378)},  # the knee: the rounded bottom runs on past it, over the lower leg
        'shin': {'pivot': (46, 30), 'tip': (52, 410)},  # one piece, knee to ankle
        'armStraight': {'pivot': (68, 45), 'tip': (100, 545)},  # the whole arm, shoulder to wrist, used when it's straight
        'foot': {'pivot': (62, 100), 'tip': (62, 138)},
        'torso': {'pivot': (140, 440), 'tip': (120, 28)},  # its faded trouser bottom laps over the thighs
        'helmet': {'pivot': (165, 372), 'tip': (150, 16), 'file': 'head'},  # head and neck: the base of the neck to the top of the head
    },
}


def mid_width(im, pivot, tip):
    """Width of the part's silhouette across the middle of its axis."""
    a = np.asarray(im.getchannel('A')) > 128
    p, t = np.array(pivot, float), np.array(tip, float)
    m = (p + t) / 2
    d = (t - p) / np.linalg.norm(t - p)
    n = np.array([-d[1], d[0]])
    inside = 0
    for s in np.arange(-max(im.size), max(im.size), 1.0):
        x, y = (m + n * s).round().astype(int)
        if 0 <= x < im.width and 0 <= y < im.height and a[y, x]:
            inside += 1
    return inside


def main(cid, folder, out):
    parts = {}
    for name, anchor in ANCHORS[cid].items():
        im = Image.open(f"{folder}/{anchor.get('file', name)}.png").convert('RGBA')
        buf = io.BytesIO()
        im.save(buf, 'WEBP', quality=90)
        parts[name] = {
            'src': 'data:image/webp;base64,' + base64.b64encode(buf.getvalue()).decode(),
            **{k: list(v) for k, v in anchor.items() if k != 'file'},
            'mid': mid_width(im, anchor['pivot'], anchor['tip']),
        }
        print(name, im.size, len(buf.getvalue()) // 1024, 'KB', 'mid', parts[name]['mid'])
    with open(out, 'w') as f:
        f.write(f'// Generated by tools/pack_parts.py: {cid}\'s painted body parts (Nano Banana), with joint points.\n')
        f.write('var PARTS = window.PARTS || {};\n')
        f.write(f'PARTS.{cid} = {json.dumps(parts)};\n')


if __name__ == '__main__':
    main(*sys.argv[1:4])
