"""Isolate character art, face it right, and resample to the game's art-pixel grid.

usage: python3 tools/prep_sprites.py <character1_png> <character2_jpg> <repo_dir>
Writes:
  <repo>/art/<id>.png             full-res cutout, transparent, facing right
  <repo>/assets/sprites/<id>.png  game-res sprite (1 px = 1 art pixel)
"""
import sys
from collections import deque
from PIL import Image

char1_path, char2_path, repo = sys.argv[1:4]


def remove_white_bg(im, thresh=228, hole_min=250):
    """Flood-fill near-white background from the border, then clear enclosed
    near-white holes larger than hole_min pixels (gaps between arm and body)."""
    im = im.convert('RGBA')
    w, h = im.size
    px = im.load()

    def bg(x, y):
        r, g, b, _ = px[x, y]
        return r > thresh and g > thresh and b > thresh

    seen = bytearray(w * h)

    def fill(sx, sy):
        region = []
        q = deque([(sx, sy)])
        seen[sy * w + sx] = 1
        while q:
            x, y = q.popleft()
            region.append((x, y))
            for nx, ny in ((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)):
                if 0 <= nx < w and 0 <= ny < h and not seen[ny * w + nx] and bg(nx, ny):
                    seen[ny * w + nx] = 1
                    q.append((nx, ny))
        return region

    for x in range(w):
        for y in (0, h - 1):
            if not seen[y * w + x] and bg(x, y):
                for p in fill(x, y):
                    px[p] = (0, 0, 0, 0)
    for y in range(h):
        for x in (0, w - 1):
            if not seen[y * w + x] and bg(x, y):
                for p in fill(x, y):
                    px[p] = (0, 0, 0, 0)
    for y in range(h):
        for x in range(w):
            if not seen[y * w + x] and bg(x, y):
                region = fill(x, y)
                if len(region) >= hole_min:
                    for p in region:
                        px[p] = (0, 0, 0, 0)
    return im


def harden_alpha(im, cut=128):
    px = im.load()
    w, h = im.size
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            px[x, y] = (r, g, b, 255) if a >= cut else (0, 0, 0, 0)
    return im


def trim(im):
    return im.crop(im.getbbox())


def feet_anchor(im):
    """x of the midpoint between the outer edges of the bottom rows (the feet)."""
    w, h = im.size
    px = im.load()
    xs = [x for y in range(int(h * 0.92), h) for x in range(w) if px[x, y][3]]
    return (min(xs) + max(xs)) / 2


# --- Character 1: native SNES-style sprite upscaled ~10.25x, already transparent, faces right.
mei = trim(Image.open(char1_path).convert('RGBA'))
mei_full = mei.copy()
block = 10.25
bw, bh = round(mei.width / block), round(mei.height / block)
mei_small = harden_alpha(mei.resize((bw, bh), Image.NEAREST))

# --- Character 2: JPEG on white, faces left -> cut out and mirror to face right.
korr = remove_white_bg(Image.open(char2_path))
korr = trim(harden_alpha(korr, 100)).transpose(Image.FLIP_LEFT_RIGHT)
korr_full = korr.copy()
target_h = 76  # taller than character 1, like the reference art
scale = target_h / korr.height
korr_small = korr.convert('RGBa').resize((round(korr.width * scale), target_h), Image.BOX).convert('RGBA')
korr_small = harden_alpha(korr_small, 110)
# Snap to a small palette taken from the art so it reads as crisp pixel art.
alpha = korr_small.getchannel('A')
pal = korr.convert('RGB').quantize(colors=18, method=Image.Quantize.MEDIANCUT)
korr_small = korr_small.convert('RGB').quantize(palette=pal, dither=Image.Dither.NONE).convert('RGBA')
korr_small.putalpha(alpha)

for cid, full, small in (('fett', mei_full, mei_small), ('worf', korr_full, korr_small)):
    full.save(f'{repo}/art/{cid}.png')
    small = trim(small)
    small.save(f'{repo}/assets/sprites/{cid}.png')
    print(cid, 'full', full.size, 'sprite', small.size, 'feet anchor x', feet_anchor(small))

# Embed the game sprites as data URIs. Images loaded from file:// would taint
# the canvas and block the per-pixel sprite pass; data URIs don't.
import base64, io, json
entries = {}
for cid in ('fett', 'worf'):
    img = Image.open(f'{repo}/assets/sprites/{cid}.png')
    buf = io.BytesIO()
    img.save(buf, 'PNG', optimize=True)
    entries[cid] = {
        'src': 'data:image/png;base64,' + base64.b64encode(buf.getvalue()).decode(),
        'w': img.width,
        'h': img.height,
        'anchorX': feet_anchor(img),
    }
with open(f'{repo}/src/sprites.js', 'w') as f:
    f.write('// Generated by tools/prep_sprites.py from the PNGs in assets/sprites/. Do not edit by hand.\n')
    f.write('// Each sprite faces right; 1 image pixel = 1 art pixel; anchorX is the x between the feet.\n')
    f.write('const SPRITE_DATA = ' + json.dumps(entries, indent=2) + ';\n')
